// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5bVcvqndjhPC8ur-NO1wGNdHeAPw3hjo',
    appId: '1:1065550321782:web:d307c4bd532138b4356757',
    messagingSenderId: '1065550321782',
    projectId: 'wemace-2cfec',
    authDomain: 'wemace-2cfec.firebaseapp.com',
    storageBucket: 'wemace-2cfec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4yi-jQJcyXS5EKCotdB9sQIUFVWM_dxE',
    appId: '1:1065550321782:android:7639de40b5864386356757',
    messagingSenderId: '1065550321782',
    projectId: 'wemace-2cfec',
    storageBucket: 'wemace-2cfec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASzr3XEL1KNk-Q9tw5nwzsux0dSnTq7fI',
    appId: '1:1065550321782:ios:a0ad83393c8ccf51356757',
    messagingSenderId: '1065550321782',
    projectId: 'wemace-2cfec',
    storageBucket: 'wemace-2cfec.appspot.com',
    iosBundleId: 'com.example.wemace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASzr3XEL1KNk-Q9tw5nwzsux0dSnTq7fI',
    appId: '1:1065550321782:ios:46e1975aa5505343356757',
    messagingSenderId: '1065550321782',
    projectId: 'wemace-2cfec',
    storageBucket: 'wemace-2cfec.appspot.com',
    iosBundleId: 'com.example.wemace.RunnerTests',
  );
}
